service: miranda-backend
provider:
  name: aws
  region: eu-south-2
  environment:
    SECRET: "secret"
  runtime: nodejs18.x
functions:
  app:
    handler: dist/lambda.handler
    events:
      - http: ANY /
      - http: ANY /{proxy+}
